apiVersion: v1
kind: Service
metadata:
  name: disease-portal-http
spec:
  ports:
    - port: 31234
      protocol: TCP
      nodePort: 31234
      targetPort: 80
  selector:
    app: disease-portal-client
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: disease-portal-client
spec:
  selector:
    matchLabels:
      app: disease-portal-client
  replicas: 1
  template:
    metadata:
      labels:
        app: disease-portal-client
    spec:
      containers:
        - name: disease-portal-client
          image: dockerhub.ebi.ac.uk/uniprot/front-end/disease-portal-client
          ports:
            - containerPort: 80
          imagePullPolicy: Always
      imagePullSecrets:
        - name: gitlab-registry
